name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: circleci/node:10

    steps:
    - uses: actions/checkout@v2

    - name: Update npm
      run: sudo npm install -g npm@latest

    - name: Cache Node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Install npm dependencies
      run: npm install

    - name: Build output
      run: npm run out

  unittest:
    needs: build
    runs-on: ubuntu-latest
    container: 
      image: circleci/node:10

    steps:
    - uses: actions/checkout@v2

    - name: Cache Node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Install npm dependencies
      run: npm install

    - name: Run tests with JUnit as reporter
      run: |
        npx jest --ci --runInBand --reporters=default --reporters=jest-junit --config=jest.config.ci.js
      env:
        JEST_JUNIT_OUTPUT: 'reports/junit/unit-test-results.xml'

  e2etest:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js 10.16.0
      uses: actions/setup-node@v2
      with:
        node-version: '10.16.0'

    - name: Cache Node modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Install npm dependencies
      run: npm install

    - name: Start localstack
      run: npm run localstack:up

    - name: Build output
      run: |
        node -v
        npm run out

    - name: Deploy functions to localstack
      run: npm run serverless

    - name: Run tests with JUnit as reporter
      run: |
        npx jest --ci --runInBand --reporters=default --reporters=jest-junit --config=jest.config.e2e.js
      env:
        JEST_JUNIT_OUTPUT: 'reports/junit/e2e-test-results.xml'

    - name: Finish localstack
      run: npm run localstack:down
